name: spell_checker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zwaldowski/cspell-action@v1
        with:
          paths: "**/*.{md,dart}"
          exclude: ".gitignore **.gen.dart **.g.dart"
